### ISSUE TITLE
Project is missing main.js

### ISSUE THREAD

**Issue by nodeflux** [bechbd/gremlin-ide#10]
Hi,

  We are doing some Neptune development on Windows and wanted to give this a shot, but were not able to get things running. After some digging around, it appears to me that perhaps main.js needs to be added to the project, but was accidentally marked to ignore in .gitignore. We added a main.js based on the boilerplate code, and were able to get up and running - happy to include or add it if this is helpful to you.

Thanks.

**Comment by bechbd** [comment]
I created a branch that has the missing main.js file in it called Issue_9_10.  I am having trouble building on my machine for a different reason but this should get you unstuck if needed.  I will take another look later this week and get this working.

**Comment by bechbd** [comment]
This fix is now merged into master
